module.exports = {
	name: 'salary sheet',
	fields: {
		progress_id: {
			name: 'Progress_Id',
			type: 'string',
			desc: '',
			unique: true,
			must: true,
			show: true, 
			required: true,
		},
		project: { 
			name: 'Project',
			type: 'string',
			desc: '',
			must: true,
			show: true,
			required: false,
		},
		member: {
			name: 'Member',
			type: 'string',
			desc: '',
			must: false,
			show: false,
		},
		identity:{
			name: 'Identity',
			type: 'string',
			desc: '',
			must: true,
			show: true,
			required: false,
		},
		pricing_method :{
			name: 'Pricing method',
			type: 'number',
			desc: '',
			must: true,
			show: true,
			required: false,
		},
		workload :{
			name: 'Workload',
			type: 'number',
			desc: '',
			must: true,
			show: true,
			required: false,
		},
		ot:{
			name: 'Overtime workload',
			type: 'number',
			desc: '',
			must: true,
			show: true,
			required: false,
		},
		ot_pay:{
			name: 'Overtime pay',
			type: 'number',
			desc: '',
			must: true,
			show: true,
			required: false,
		},
		salary:{
			name: 'Total Salary',
			type: 'number',
			desc: '',
			must: true,
			show: true,
			required: false,
		},
		starting_time: {
			name: 'Starting time',
			type: 'datetime',
			must: true,
			show: true,
			
		},
		end_time: {
			name: 'End Time',
			type: 'datetime',
			must: true,
			show: true,
		},
	}
};